frontend/models/Employee.php
<?php

namespace frontend\models;

use Yii;

class Employee extends \yii\db\ActiveRecord
{
    /**  
     * @inheritdoc  
     */
    public static function tableName()
    {
        return 'employee';
    }

    /**  
     * @inheritdoc  
     */
    public function rules()
    {
        return [
            [['first_name', 'last_name', 'email', 'pwd', 'cpwd'], 'required'],
            [['first_name', 'last_name'], 'string', 'max' => 30],
            ['email', 'email'],
            ['cpwd', 'compare', 'compareAttribute' => 'pwd'],
            [['first_name', 'last_name', 'email'], 'filter', 'filter' => 'trim', 'skipOnArray' => true],
            [['email'], 'string', 'max' => 50],
            [['pwd', 'cpwd'], 'string', 'max' => 20],
            [['photo'], 'string', 'max' => 200],
            [['email'], 'unique'],
        ];
    }
}

frontend/controllers/EmployeeController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Employee;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;
use yii\data\Pagination;
use \yii\web\Response;
use yii\helpers\Html;


/**  
 * manual CRUD  
 **/
class EmployeeController extends Controller
{
    /**  
     * Create  
     */
    public function actionCreate()
    {

        $model = new Employee();

        // new record   
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            echo 1;
        } else {
            return $this->renderAjax('create', [
                'model' => $model
            ]);
        }
    }
    public function actionIndex()
    {
        $query = Employee::find();
        $pagination = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);
        $emp = $query->orderBy('first_name')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->asArray()
            ->all();
        return $this->render('index', ['model' => $emp, 'pagination' => $pagination,]);
    }
    public function actionUpdate($id)
    {

        $model = Employee::find()->where(['id' => $id])->one();

        // $id not found in database   
        if ($model === null)
            throw new NotFoundHttpException('The requested page does not exist.');

        // update record   
        if ($model->load(Yii::$app->request->post())) {
            $model->photo = UploadedFile::getInstance($model, 'photo');
            $fileName = time() . '.' . $model->image->extension;
            $model->photo->saveAs('assets/images/' . $fileName);
            $model->photo = $fileName;
            //$data=CHtml::listData($model,'cityid','name');
            $model->save();
            return $this->redirect(['index', 
             'id' => $model->id]);
        } else {
            return json_encode($this->renderAjax('update', ['model' => $model]));
        }
    }
    public function actionView($id)
    {
        $output = "";
        //$id = $_POST('id');
        $model = Employee::find()->where(['id' => $id])->one();

        // $id not found in database   
        if ($model === null)
            throw new NotFoundHttpException('The requested page does not exist.');

    
        return json_encode($this->renderAjax('view', ['model' => $model]));
    }
    public function actionDelete($id)
    {
        $model = Employee::findOne($id);

        // $id not found in database   
        if ($model === null)
            throw new NotFoundHttpException('The requested page does not exist.');

        // delete record   
        $model->delete();
        return json_encode("1");
        //return json_encode($this->redirect(['index']));
    }
    public function actionGrid()
    {
        return $this->render('resultgrid');
    }
}

frontend/views/employee/create.php
<?= $this->renderAjax('employee_view', [
    'model' => $model,
]) ?>  

frontend/views/employee/employee_view.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<!-- ['id' => $model->formName()] -->
<!-- [
    'options' => [
        'id' => 'create-product-form'
    ]
] -->
<h1>Add User</h1>
<?php $form = ActiveForm::begin(['id' => $model->formName()]); ?>

<?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'pwd')->passwordInput(['maxlength' => true])->label('Password') ?>

<?= $form->field($model, 'cpwd')->passwordInput(['maxlength' => true])->label('Confirm Password') ?>

<?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']); ?>

<?php ActiveForm::end(); ?>

<?php $script = <<< JS
$('form#{$model->formName()}').on('beforeSubmit',function(e)
{
    var \$form=$(this);
    $.post(
        \$form.attr("action"),
        \$form.serialize()
    )
    .done(function (result) {
        if(result==1)
        {
            //$(\$form).trigger("reset");
            $(document).find('#modal').modal('hide');
            $.pjax.reload({container:'#index'});
        }            
        else
        {
            $(\$form).trigger("reset");
            $("#message").html(result.message);
        }
    }).fail(function()
    {
        console.log("server-error");
    })
    return false;
})
JS;
$this->registerJs($script);
?>

frontend/views/employee/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\Modal;
use yii\widgets\Pjax;
use yii\widgets\LinkPager;

?>
<style> 
 h1
      {
        text-align:center;
        background-color:orange;
        color:black;
      }  
table th,td{   
    padding: 20px; 
    margin:30px;
    text-align:center;  
}  
th
{
    background-color:skyblue;
    color:red;
} 
</style>   
<h1>Yii2 CRUD Application Design</h1><br>
<?= Html::button('Add User', ['value' => Url::to('index.php?r=employee/create'), 'class' => 'addButton btn btn-success', 'onclick' => 'viewClick(this.getAttribute("class"))']); ?>

<?php
Modal::begin([
    //'header' => '<h4>Add User</h4>',
    'id' => 'modal',
    'size' => 'modal-lg',
]);
echo "<div id='modalContent'></div>";
Modal::end();
?>
<?php Pjax::begin(['id' => 'index']); ?>
<br><br>
<table border="1" class='table table-striped table-hover table-bordered'>
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        </th>
        <th>Action</th>
    </tr>
    <?php foreach ($model as $field) :
        $encodedData = json_encode($field);
    ?>
        <tr>
            <td><?= $field['first_name']; ?></td>
            <td><?= $field['last_name']; ?></td>
            <td><?= $field['email']; ?></td>
            <td>
                <?= Html::button('View', ['value' => '', 'class' => 'viewButton btn btn-success', 'onclick' => 'viewClick(this.getAttribute("class"),this)', 'data-model' => $encodedData]); ?>
                <?= Html::button('Edit', ['value' => '', 'class' => 'editButton btn btn-primary', 'onclick' => 'viewClick(this.getAttribute("class"),this)', 'data-model' => $encodedData]); ?>
                <?= Html::button('Delete', ['value' => '', 'class' => 'deleteButton btn btn-danger', 'onclick' => 'viewClick(this.getAttribute("class"),this)', 'data-model' => $encodedData]); ?>

        </tr>
    <?php endforeach; ?>
</table>
<?= LinkPager::widget(['pagination' => $pagination]) ?>
<?php Pjax::end(); ?>

frontend/views/employee/resultgrid.php
<?php

use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use frontend\models\Employee;
use yii\widgets\Pjax;
use yii\helpers\Html;

$dataProvider = new ActiveDataProvider([
    'query' => Employee::find(),
    'pagination' => [
        'pageSize' => 2,
    ],

]);
?>
<h2>Employee Data</h2>
<?php
Pjax::begin([
    'id' => 'pjax-list',
    'enablePushState' => false,
    'enableReplaceState' => false,
]);
echo GridView::widget([
    'dataProvider' => $dataProvider,
    // 'options' => [
    //     'data-pjax' => 0
    // ],
    'columns' => [
        'id',
        'first_name',
        [
            'attribute' => 'email',
            'label' => 'Email Address'
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'header' => 'Action',
            'headerOptions' => ['width' => '80'],
            'buttons' => [
                'update' => function ($url, $model) {
                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                        'title' => Yii::t('app', 'lead-update'),
                        'data-pjax' => '0',

                    ]);
                },

                'delete' => function ($url, $model) {

                    // return ((Yii::$app->user->can("employee/delete")) ? Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, ['title' => Yii::t('app', 'Delete'), 'data' => ['confirm' => 'Are you sure you want to delete this item?', 'method' => 'post'], 'data-ajax' => '1']) : '');

                    return ((Yii::$app->user->can("/student/stu/delete")) ? Html::a('<span  class="glyphicon glyphicon-trash"></span>', false, ['class' => 'ajaxDelete', 'delete-url' => $url, 'pjax-container' => 'pjax-list', 'title'  => Yii::t('app', 'Delete'), 'data' => ['confirm' => 'Are you  sure you want to delete this item?']]) : '');
                }
            ],
        ]

    ]
]);
Pjax::end(); ?>
<?php $script = <<< JS
$(function () {

$(document).on('click', '.ajaxDelete', function () {
    alert('we are in delete');
    var deleteUrl = $(this).attr('delete-url');

    var pjaxContainer = $(this).attr('pjax-list');

    $.ajax({

        url: deleteUrl,

        type: "post",

        dataType: 'json',

        error: function (xhr, status, error) {

            alert('There was an error with your request.' + xhr.responseText);

        }

    }).done(function (data) {

        $.pjax.reload({ container: '#' + $.trim(pjaxContainer) });

    });

});

});


JS;
$this->registerJs($script);
?>

frontend/views/employee/update.php
<?= $this->render('update_view', [
    'model' => $model,
]) ?>  

frontend/views/employee/update_view.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>
<h2>Update User</h2>
<img src='assets/images/<?= $model->photo; ?>' height="200" width="200">
<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data'], 'id' => 'update-form']); ?>

<?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>

<?= $form->field($model, 'photo')->fileInput()->label('Profile Photo'); ?>

<?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']); ?>

<?php ActiveForm::end(); ?>
<?php $script = <<< JS

$('#update-form').on('beforeSubmit',function(e)
{
e.preventDefault();
var formData = new FormData($('form')[0]);
$.ajax({
url:$('#update-form').attr('action'),
type: 'POST',
data: formData,
contentType: false,
cache: false,
processData: false,
dataType: 'json',
success: function (data) {
console.log(data);
$('#modal').modal('hide');
location.reload();
}
})
JS;
$this->registerJs($script);
?>

frontend/views/employee/view.php
<?php

use yii\helpers\Html;
use yii\widgets\Pjax;
?>
<?php Pjax::begin(['id' => 'view']); ?>
<h1>View User</h1>
<img src='assets/images/<?= $model->photo; ?>' height="200" width="200">
<table>
    <tr>
        <td><?= $model->first_name; ?> <?= $model->last_name; ?></td>

    </tr>
    <tr>
        <td><?= $model->email; ?></td>
    </tr>
</table>
<?php Pjax::end(); ?>